$kind: http-request
name: Eliminar tarea erronea
url: "{{baseUrl}}/tasks/1"
method: DELETE
auth:
  credentials:
    - key: token
      value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsInJvbGUiOiJhZG1pbiIsIm5hbWUiOiJBbmRyw6lzIiwiaWF0IjoxNzc1NTI1OTM4LCJleHAiOjE3NzU1MzMxMzh9.GLtBOSM5O3DfPkjkbLIr0n8eMVk_rQ9xqOAK2otaucg
  type: bearer
order: 4000
