$kind: http-request
name: Listar tareas por id
url: "{{urlBase}}/tasks/2"
method: GET
auth:
  credentials:
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsInJvbGUiOiJhZG1pbiIsIm5hbWUiOiJBbmRyw6lzIiwiaWF0IjoxNzc1NTI1OTM4LCJleHAiOjE3NzU1MzMxMzh9.GLtBOSM5O3DfPkjkbLIr0n8eMVk_rQ9xqOAK2otaucg
  type: bearer
order: 1482
